### ISSUE TITLE
qwen_14b_chat build error

### ISSUE THREAD

**Issue by dangerous-xu** [Tlntin/Qwen-TensorRT-LLM#100]
## Error Info
root@99b1f5360539:/app/tensorrt_llm/examples/qwen/qwen# python3 build.py --remove_input_padding --enable_context_fmha
[TensorRT-LLM] TensorRT-LLM version: 0.8.0[03/27/2024-06:29:44] [TRT-LLM] [I] Serially build TensorRT engines.
[03/27/2024-06:29:44] [TRT] [I] [MemUsageChange] Init CUDA: CPU +14, GPU +0, now: CPU 123, GPU 5539 (MiB)
[03/27/2024-06:29:57] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1973, GPU +350, now: CPU 2232, GPU 5889 (MiB)
[03/27/2024-06:29:57] [TRT-LLM] [W] Invalid timing cache, using freshly created one
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/qwen/qwen/build.py", line 770, in <module>
    build(0, args)
  File "/app/tensorrt_llm/examples/qwen/qwen/build.py", line 735, in build
    engine = build_rank_engine(
  File "/app/tensorrt_llm/examples/qwen/qwen/build.py", line 498, in build_rank_engine
    tensorrt_llm_qwen = QWenForCausalLM_TRT(
  File "/app/tensorrt_llm/examples/qwen/qwen/model.py", line 1027, in __init__
    super().__init__(
  File "/app/tensorrt_llm/examples/qwen/qwen/model.py", line 885, in __init__
    self.layers = ModuleList([
  File "/app/tensorrt_llm/examples/qwen/qwen/model.py", line 886, in <listcomp>
    QWenBlock(
  File "/app/tensorrt_llm/examples/qwen/qwen/model.py", line 692, in __init__
    self.attention = QWenAttention(
  File "/app/tensorrt_llm/examples/qwen/qwen/model.py", line 317, in __init__
    self.dense = RowLinear(hidden_size,
TypeError: RowLinear.__init__() got an unexpected keyword argument 'instance_id'

## Environment
```
docker pull nvcr.io/nvidia/tritonserver:24.02-trtllm-python-py3
pip install tensorrt_llm==0.8.0 --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121
cd /app/tensorrt_llm/examples/qwen/
pip install -r requirements.txt
```

## Model
qwen_14b_chat

## GPU
NVIDIA A800

## Build Code
```
python build.py --hf_model_dir /app/tensorrt_llm/examples/qwen/qwen/qwen_14b_chat/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --output_dir /app/tensorrt_llm/examples/qwen/qwen/qwen_14b_chat/trt_engines/fp16/1-gpu/
```

Any suggestion?

**Comment by Tlntin** [comment]
qwen1系列请暂时用0.7.0分支，0.8.0还未更新qwen1

**Comment by dangerous-xu** [comment]
> qwen1系列请暂时用0.7.0分支，0.8.0还未更新qwen1

非常感谢您的回复！
另外，我还测试了qwen1.5_14b_chat，使用的最新代码，docker中按照教程升级了transformers>=4.37.0（与tensorrt-llm版本0.8.0不兼容），运行build后也出现了与上文相同的报错。
`TypeError: RowLinear.init() got an unexpected keyword argument 'instance_id'`
请教一下您是否有什么建议，您测试的时候qwen1.5_14b_chat 模型FP16是怎么转换成功

**Comment by Tlntin** [comment]
请用/app/tensorrt_llm/examples/qwen2目录做qwen1.5的测试。
