### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Bilibili-Mikoto** [Tlntin/Qwen-TensorRT-LLM#114]
您好，请问下按照readme的步骤，在进行  编译 int8 (weight only) 出现如下问题，请问怎么解决
root@67fdc7ba310f:/app/tensorrt_llm/examples/qwen2# python3 build.py --use_weight_only --weight_only_precision=int8
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
[TensorRT-LLM] TensorRT-LLM version: 0.8.0[05/05/2024-13:15:57] [TRT-LLM] [I] Serially build TensorRT engines.
[05/05/2024-13:15:57] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 131, GPU 2329 (MiB)
[05/05/2024-13:15:58] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1820, GPU +319, now: CPU 2087, GPU 2638 (MiB)
[05/05/2024-13:15:58] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[05/05/2024-13:15:58] [TRT-LLM] [I] Loading FT QWen ... from /app/tensorrt_llm/examples/qwen2/c-model/qwen1.5_7b_chat/1-gpu
[05/05/2024-13:15:58] [TRT-LLM] [I] Loading weights from FT...
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/qwen2/build.py", line 885, in <module>
    build(0, args)
  File "/app/tensorrt_llm/examples/qwen2/build.py", line 862, in build
    engine = build_rank_engine(
  File "/app/tensorrt_llm/examples/qwen2/build.py", line 711, in build_rank_engine
    load_from_ft(
  File "/app/tensorrt_llm/examples/qwen2/weight.py", line 108, in load_from_ft
    ) = parse_ft_config(Path(dir_path) / "config.ini")
  File "/app/tensorrt_llm/examples/qwen2/weight.py", line 54, in parse_ft_config
    vocab_size = qwen_config.getint("qwen", "vocab_size")
  File "/usr/lib/python3.10/configparser.py", line 820, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 810, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 805, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.10/configparser.py", line 783, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.10/configparser.py", line 1154, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'qwen'

**Comment by Tlntin** [comment]
清理掉当前路径的`c-model`文件夹
