### ISSUE TITLE
在使用脚本qwen   build时出现bug

### ISSUE THREAD

**Issue by zixuxu000** [Tlntin/Qwen-TensorRT-LLM#117]
bug如下
```python
  File "/root/autodl-tmp/Qwen-TensorRT-LLM/examples/qwen/build.py", line 770, in <module>
    build(0, args)
  File "/root/autodl-tmp/Qwen-TensorRT-LLM/examples/qwen/build.py", line 735, in build
    engine = build_rank_engine(
  File "/root/autodl-tmp/Qwen-TensorRT-LLM/examples/qwen/build.py", line 498, in build_rank_engine
    tensorrt_llm_qwen = QWenForCausalLM_TRT(
  File "/root/autodl-tmp/Qwen-TensorRT-LLM/examples/qwen/model.py", line 1027, in __init__
    super().__init__(
  File "/root/autodl-tmp/Qwen-TensorRT-LLM/examples/qwen/model.py", line 885, in __init__
    self.layers = ModuleList([
  File "/root/autodl-tmp/Qwen-TensorRT-LLM/examples/qwen/model.py", line 886, in <listcomp>
    QWenBlock(
  File "/root/autodl-tmp/Qwen-TensorRT-LLM/examples/qwen/model.py", line 692, in __init__
    self.attention = QWenAttention(
  File "/root/autodl-tmp/Qwen-TensorRT-LLM/examples/qwen/model.py", line 317, in __init__
    self.dense = RowLinear(hidden_size,
TypeError: RowLinear.__init__() got an unexpected keyword argument 'instance_id'
```
环境如下
```shell
tensorrt-llm                   0.8.0
torch                          2.1.0
transformers                   4.36.1
transformers-stream-generator  0.0.5

**Comment by Tlntin** [comment]
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/28218658/3bb4e676-c469-4394-a400-bb7a76f7a5a3)
如果是需要用tensorrt-llm 0.8.0, 建议用qwen1.5，或者将tensorrt-llm降级到0.7.0也行。

**Comment by zixuxu000** [comment]
感谢回复！
我使用qwen1.5  14b进行build，似乎也会出现错误,硬件设备为单卡4090
执行脚本如下
```
python /root/autodl-tmp/Qwen-TensorRT-LLM/examples/qwen2/build.py \
    --remove_input_padding \
    --enable_context_fmha
```
错误如下
```shell
[05/15/2024-19:25:10] [TRT-LLM] [I] HF QWen loaded. Total time: 00:00:00
[05/15/2024-19:25:10] [TRT-LLM] [I] Loading weights from HF QWen...
Converting...: 100%|█████████████████████████| 483/483 [00:04<00:00, 105.13it/s]
[05/15/2024-19:25:15] [TRT-LLM] [I] Weights loaded. Total time: 00:00:04
[05/15/2024-19:25:16] [TRT-LLM] [I] Set bert_attention_plugin to None.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set gpt_attention_plugin to None.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set gemm_plugin to None.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set smooth_quant_gemm_plugin to None.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set identity_plugin to None.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set layernorm_quantization_plugin to None.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set rmsnorm_quantization_plugin to None.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set nccl_plugin to None.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set lookup_plugin to None.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set lora_plugin to None.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set weight_only_groupwise_quant_matmul_plugin to None.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set weight_only_quant_matmul_plugin to None.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set quantize_per_token_plugin to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set quantize_tensor_plugin to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set context_fmha to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set context_fmha_fp32_acc to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set paged_kv_cache to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set remove_input_padding to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set use_custom_all_reduce to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set multi_block_mode to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set enable_xqa to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set attention_qk_half_accumulation to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set use_paged_context_fmha to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set use_context_fmha_for_generation to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set gpt_attention_plugin to float16.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set gemm_plugin to float16.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set context_fmha to True.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set context_fmha_fp32_acc to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set remove_input_padding to True.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set gpt_attention_plugin to float16.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set gemm_plugin to float16.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set remove_input_padding to True.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set paged_kv_cache to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set tokens_per_block to 128.
[05/15/2024-19:25:16] [TRT-LLM] [I] Set use_custom_all_reduce to False.
[05/15/2024-19:25:16] [TRT-LLM] [I] Build TensorRT engine qwen2_float16_tp1_rank0.engine
[05/15/2024-19:25:16] [TRT] [W] Unused Input: position_ids
[05/15/2024-19:25:16] [TRT] [W] Detected layernorm nodes in FP16.
[05/15/2024-19:25:16] [TRT] [W] Running layernorm after self-attention in FP16 may cause overflow. Exporting the model to the latest available ONNX opset (later than opset 17) to use the INormalizationLayer, or forcing layernorm layers to run in FP32 precision can help with preserving accuracy.
[05/15/2024-19:25:16] [TRT] [W] [RemoveDeadLayers] Input Tensor position_ids is unused or used only at compile-time, but is not being removed.
[05/15/2024-19:25:16] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 29135, GPU 733 (MiB)
[05/15/2024-19:25:16] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 29137, GPU 743 (MiB)
[05/15/2024-19:25:16] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
[05/15/2024-19:25:16] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
Killed

**Comment by Tlntin** [comment]
> 感谢回复！ 我使用qwen1.5 14b进行build，似乎也会出现错误,硬件设备为单卡4090 环境是在autodl自动配置的大佬的镜像 执行脚本如下
> 
> ```
> python /root/autodl-tmp/Qwen-TensorRT-LLM/examples/qwen2/build.py \
>     --remove_input_padding \
>     --enable_context_fmha
> ```
> 
> 错误如下
> 
> ```shell
> [05/15/2024-19:25:10] [TRT-LLM] [I] HF QWen loaded. Total time: 00:00:00
> [05/15/2024-19:25:10] [TRT-LLM] [I] Loading weights from HF QWen...
> Converting...: 100%|█████████████████████████| 483/483 [00:04<00:00, 105.13it/s]
> [05/15/2024-19:25:15] [TRT-LLM] [I] Weights loaded. Total time: 00:00:04
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set bert_attention_plugin to None.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set gpt_attention_plugin to None.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set gemm_plugin to None.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set smooth_quant_gemm_plugin to None.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set identity_plugin to None.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set layernorm_quantization_plugin to None.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set rmsnorm_quantization_plugin to None.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set nccl_plugin to None.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set lookup_plugin to None.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set lora_plugin to None.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set weight_only_groupwise_quant_matmul_plugin to None.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set weight_only_quant_matmul_plugin to None.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set quantize_per_token_plugin to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set quantize_tensor_plugin to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set context_fmha to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set context_fmha_fp32_acc to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set paged_kv_cache to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set remove_input_padding to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set use_custom_all_reduce to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set multi_block_mode to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set enable_xqa to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set attention_qk_half_accumulation to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set use_paged_context_fmha to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set use_context_fmha_for_generation to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set gpt_attention_plugin to float16.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set gemm_plugin to float16.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set context_fmha to True.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set context_fmha_fp32_acc to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set remove_input_padding to True.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set gpt_attention_plugin to float16.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set gemm_plugin to float16.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set remove_input_padding to True.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set paged_kv_cache to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set tokens_per_block to 128.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Set use_custom_all_reduce to False.
> [05/15/2024-19:25:16] [TRT-LLM] [I] Build TensorRT engine qwen2_float16_tp1_rank0.engine
> [05/15/2024-19:25:16] [TRT] [W] Unused Input: position_ids
> [05/15/2024-19:25:16] [TRT] [W] Detected layernorm nodes in FP16.
> [05/15/2024-19:25:16] [TRT] [W] Running layernorm after self-attention in FP16 may cause overflow. Exporting the model to the latest available ONNX opset (later than opset 17) to use the INormalizationLayer, or forcing layernorm layers to run in FP32 precision can help with preserving accuracy.
> [05/15/2024-19:25:16] [TRT] [W] [RemoveDeadLayers] Input Tensor position_ids is unused or used only at compile-time, but is not being removed.
> [05/15/2024-19:25:16] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 29135, GPU 733 (MiB)
> [05/15/2024-19:25:16] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 29137, GPU 743 (MiB)
> [05/15/2024-19:25:16] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
> [05/15/2024-19:25:16] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
> Killed
> ```

你的结尾是Killed,大概是内存不足导致啥后台了，你可以看看readme关于14b模型的cpu内存要求。

**Comment by zixuxu000** [comment]
之前可以编译成功，今天想换一下参数重新编译一下，出现了下面的问题
好奇怪，前两天build成功了
```shell
[05/20/2024-19:41:01] [TRT-LLM] [I] Set tokens_per_block to 128.
[05/20/2024-19:41:01] [TRT-LLM] [I] Set gpt_attention_plugin to float16.
[05/20/2024-19:41:01] [TRT-LLM] [I] Set gemm_plugin to float16.
[05/20/2024-19:41:01] [TRT-LLM] [I] Set remove_input_padding to True.
[05/20/2024-19:41:01] [TRT-LLM] [I] Set paged_kv_cache to True.
[05/20/2024-19:41:01] [TRT-LLM] [I] Set tokens_per_block to 128.
[05/20/2024-19:41:01] [TRT-LLM] [I] Set use_custom_all_reduce to False.
[05/20/2024-19:41:01] [TRT-LLM] [I] Build TensorRT engine qwen2_float16_tp1_rank0.engine
[05/20/2024-19:41:01] [TRT] [W] Unused Input: position_ids
[05/20/2024-19:41:01] [TRT] [W] Detected layernorm nodes in FP16.
[05/20/2024-19:41:01] [TRT] [W] Running layernorm after self-attention in FP16 may cause overflow. Exporting the model to the latest available ONNX opset (later than opset 17) to use the INormalizationLayer, or forcing layernorm layers to run in FP32 precision can help with preserving accuracy.
[05/20/2024-19:41:01] [TRT] [W] [RemoveDeadLayers] Input Tensor position_ids is unused or used only at compile-time, but is not being removed.
[05/20/2024-19:41:01] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 16838, GPU 23206 (MiB)
[05/20/2024-19:41:01] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 16840, GPU 23216 (MiB)
[05/20/2024-19:41:01] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
[05/20/2024-19:41:01] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
[05/20/2024-19:41:01] [TRT] [E] 9: Skipping tactic 0x0000000000000000 due to exception Assertion engine failed. 
[05/20/2024-19:41:02] [TRT] [E] 2: [virtualMemoryBuffer.cpp::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[05/20/2024-19:41:02] [TRT] [W] Requested amount of GPU memory (12888047616 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[05/20/2024-19:41:02] [TRT] [W] UNSUPPORTED_STATESkipping tactic 0 due to insufficient memory on requested size of 12888047616 detected for tactic 0x0000000000000000.
[05/20/2024-19:41:02] [TRT] [E] 10: Could not find any implementation for node {ForeignNode[Qwen2ForCausalLM/embed_tokens/vocab_embedding/CONSTANT_0...Qwen2ForCausalLM/layers/0/input_layernorm/ELEMENTWISE_PROD_0]}.
[05/20/2024-19:41:02] [TRT] [E] 10: [optimizer.cpp::computeCosts::4048] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[Qwen2ForCausalLM/embed_tokens/vocab_embedding/CONSTANT_0...Qwen2ForCausalLM/layers/0/input_layernorm/ELEMENTWISE_PROD_0]}.)
[05/20/2024-19:41:02] [TRT-LLM] [E] Engine building failed, please check the error log.
[05/20/2024-19:41:03] [TRT-LLM] [I] Serializing engine to /root/autodl-tmp/qwen1.5-7b-engine/rank0.engine...
Traceback (most recent call last):
  File "/root/autodl-tmp/Qwen-TensorRT-LLM/examples/qwen2/build.py", line 884, in <module>
    build(0, args)
  File "/root/autodl-tmp/Qwen-TensorRT-LLM/examples/qwen2/build.py", line 865, in build
    engine.save(args.output_dir)
  File "/root/miniconda3/lib/python3.10/site-packages/tensorrt_llm/runtime/engine.py", line 60, in save
    serialize_engine(
  File "/root/miniconda3/lib/python3.10/site-packages/tensorrt_llm/runtime/engine.py", line 18, in serialize_engine
    f.write(engine)
TypeError: a bytes-like object is required, not 'NoneType'
