### ISSUE TITLE
tp_size=4 build 报错

### ISSUE THREAD

**Issue by mogoxx** [Tlntin/Qwen-TensorRT-LLM#118]
**RuntimeError: [TensorRT-LLM][ERROR] Assertion failed: The number of rows must be a multiple of 64 but the number of rows is 3424.** 

build命令

```
python3 build.py --hf_model_dir /model/Qwen1.5-14B-Chat \
                --dtype float16 \
                --remove_input_padding \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
                --use_inflight_batching \
                --max_input_len 6144 \
                --max_new_tokens 2048 \
                --max_batch_size 8 \
                --world_size 4 \
                --tp_size 4 \
                --use_weight_only \
                --weight_only_precision=int8 \
                --output_dir /model/trt_engines/int8/4-3090-6k2k/ \
                --parallel_build
```
Traceback (most recent call last):
  File "/app/Qwen-TensorRT-LLM/examples/qwen2/build.py", line 772, in <module>
    mp.spawn(build, nprocs=args.world_size, args=(args,))
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/app/Qwen-TensorRT-LLM/examples/qwen2/build.py", line 741, in build
    engine = build_rank_engine(
  File "/app/Qwen-TensorRT-LLM/examples/qwen2/build.py", line 592, in build_rank_engine
    load_from_hf_qwen(
  File "/app/Qwen-TensorRT-LLM/examples/qwen2/weight.py", line 664, in load_from_hf_qwen
    ) = torch.ops.fastertransformer.symmetric_quantize_last_axis_of_batched_matrix(
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: [TensorRT-LLM][ERROR] Assertion failed: The number of rows must be a multiple of 64 but the number of rows is 3424. (/home/jenkins/agent/workspace/LLM/release-0.7/L0_MergeRequest/tensorrt_llm/cpp/tensorrt_llm/kernels/cutlass_kernels/cutlass_preprocessors.cpp:501)

**Comment by Tlntin** [comment]
14b的参数没办法整除4，所以这个没办法。

**Comment by mogoxx** [comment]
好的
