### ISSUE TITLE
AttributeError: '_Runtime' object has no attribute 'address'

### ISSUE THREAD

**Issue by xiamaozi11** [Tlntin/Qwen-TensorRT-LLM#48]
Loading engine from /app/trt_engines/fp16/1-gpu/Qwen-7B-Chat_float16_tp1_rank0.engine
[12/17/2023-10:42:55] [TRT] [E] 6: The engine plan file is generated on an incompatible device, expecting compute 8.6 got compute 8.0, please rebuild.
[12/17/2023-10:42:55] [TRT] [E] 2: [engine.cpp::deserializeEngine::982] Error Code 2: Internal Error (Assertion engine->deserialize(start, size, allocator, runtime) failed. )
Traceback (most recent call last):
  File "/app/llmqa2.py", line 98, in <module>
    qa()
  File "/app/llmqa2.py", line 43, in qa
    decoder = QWenForCausalLMGenerationSession(
  File "/app/run.py", line 40, in __init__
    super().__init__(
  File "/app/tensorrt_llm/tensorrt_llm/runtime/generation.py", line 306, in __init__
    self.runtime = _Runtime(engine_buffer, mapping)
  File "/app/tensorrt_llm/tensorrt_llm/runtime/generation.py", line 143, in __init__
    self.__prepare(mapping, engine_buffer)
  File "/app/tensorrt_llm/tensorrt_llm/runtime/generation.py", line 161, in __prepare
    assert self.engine is not None
AssertionError
Exception ignored in: <function _Runtime.__del__ at 0x7f9859bab7f0>
Traceback (most recent call last):
  File "/app/tensorrt_llm/tensorrt_llm/runtime/generation.py", line 232, in __del__
    cudart.cudaFree(self.address)
AttributeError: '_Runtime' object has no attribute 'address'

**Comment by Tlntin** [comment]
The engine plan file is generated on an incompatible device, expecting compute 8.6 got compute 8.0, please rebuild.

**Comment by xiamaozi11** [comment]
cpu转能解决这个问题不

**Comment by Tlntin** [comment]
> cpu转能解决这个问题不

并不支持cpu😅，你的问题在于编译的Engine和运行的Engine，用的gpu不一样，这样是不行的。
TensorRT-LLM对环境，硬件要求很严格，编译和运行必须是同gpu，同环境才行。

**Comment by xiamaozi11** [comment]
内存使用率能低点转trt么，29G内存，转qwen-7b会kill

**Comment by Tlntin** [comment]
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/28218658/07d42826-c593-46ed-beb2-0420cf525565)
