### ISSUE TITLE
Qwen-14B-chat 多batch 报错

### ISSUE THREAD

**Issue by zshfeng00** [Tlntin/Qwen-TensorRT-LLM#55]
你好，我在跑Qwen-14B-Chat 多batch的时候，会报错，跑Qwen-7B-Chat 是没这个问题，麻烦大佬们帮忙看看
一、build命令
python build.py --hf_model_dir /mnt/workspace/model_hub/third_party/Qwen-14B-Chat \
                --dtype float16 \
                --max_batch_size 64 \
                --max_input_len 2048 \
                --max_new_tokens 2048 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --output_dir ./Qwen-14B-Chat/trt_engines/fp16/1-gpu/

二、报错信息
Namespace(backend='trt_llm', dataset='/mnt/workspace/zsf/code/lmdeploy/lmdeploy/benchmark/dataset_100.txt', hf_model_dir='/mnt/nas_public_data/model_hub/third_party/Qwen-14B-Chat', tokenizer_dir='/mnt/nas_public_data/model_hub/third_party/Qwen-14B-Chat', engine_dir='./Qwen-14B-Chat/trt_engines/fp16/1-gpu', n=1, num_prompts=16, seed=0, hf_max_batch_size=1, trt_max_batch_size=8, chat_format='chatml')
Loading engine from ./Qwen-14B-Chat/trt_engines/fp16/1-gpu/qwen_float16_tp1_rank0.engine
  0%|                                                                                                                                                  | 0/16 [00:00<?, ?it/s][12/27/2023-11:10:19] [TRT] [E] 3: [executionContext.cpp::setInputShape::2278] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2278, condition: engineDims.d[i] == dims.d[i] Static dimension mismatch while setting input shape.)
 44%|███████████████████████████████████████████████████████████▉                                                                             | 7/16 [00:00<00:00, 104.02it/s]
Traceback (most recent call last):
  File "/mnt/workspace/zsf/code/TensorRT-LLM/Qwen-TensorRT-LLM/examples/qwen/benchmark.py", line 475, in <module>
    main(args)
  File "/mnt/workspace/zsf/code/TensorRT-LLM/Qwen-TensorRT-LLM/examples/qwen/benchmark.py", line 358, in main
    elapsed_time, total_num_tokens, sum_total_generate_tokens= run_trt_llm(
  File "/mnt/workspace/zsf/code/TensorRT-LLM/Qwen-TensorRT-LLM/examples/qwen/benchmark.py", line 173, in run_trt_llm
    output_ids = decoder.generate(
  File "/mnt/workspace/zsf/code/TensorRT-LLM/Qwen-TensorRT-LLM/examples/qwen/run.py", line 135, in generate
    output_ids = self.decode(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 558, in wrapper
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 2109, in decode
    return self.decode_regular(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1859, in decode_regular
    should_stop, next_step_buffer, tasks, context_lengths, host_context_lengths, attention_mask, logits, encoder_input_lengths = self.handle_per_step(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1617, in handle_per_step
    self.runtime._set_shape(context, ctx_shape)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 210, in _set_shape
    raise ValueError(
ValueError: Couldn't assign input_ids with shape torch.Size([8, 789]), engine supports [min, opt, max] = [(1, 1), (1, 64), (1, 131072)]

**Comment by Tlntin** [comment]
--remove_input_padding
这个选项代表去除padding，加上后就不支持多batch了。

**Comment by zshfeng00** [comment]
去掉是可以了，感谢

**Comment by Tlntin** [comment]
不客气
