### ISSUE TITLE
qwen-14b int4-awq 量化失败

### ISSUE THREAD

**Issue by zshfeng00** [Tlntin/Qwen-TensorRT-LLM#64]
python build.py --hf_model_dir /mnt/workspace/model_hub/third_party/Qwen-7B-Chat \
                --quant_ckpt_path ./qwen_7b_4bit_gs128_awq.pt \
                --use_weight_only \
                --weight_only_precision int4_awq \
                --per_group \
                --max_batch_size 32 \
                --max_input_len 2048 \
                --max_new_tokens 2048 \

报错信息：
Traceback (most recent call last):
  File "/mnt/workspace/zsf/code/TensorRT-LLM/Qwen-TensorRT-LLM-v0.5.0/Qwen-TensorRT-LLM/qwen/build.py", line 776, in <module>
    build(0, args)
  File "/mnt/workspace/zsf/code/TensorRT-LLM/Qwen-TensorRT-LLM-v0.5.0/Qwen-TensorRT-LLM/qwen/build.py", line 740, in build
    engine = build_rank_engine(
  File "/mnt/workspace/zsf/code/TensorRT-LLM/Qwen-TensorRT-LLM-v0.5.0/Qwen-TensorRT-LLM/qwen/build.py", line 567, in build_rank_engine
    load_func(tensorrt_llm_qwen=tensorrt_llm_qwen,
  File "/mnt/workspace/zsf/code/TensorRT-LLM/Qwen-TensorRT-LLM-v0.5.0/Qwen-TensorRT-LLM/qwen/weight.py", line 1176, in load_from_awq_qwen
    process_and_assign_weight(model_params, mPrefix, mOp, 1)
  File "/mnt/workspace/zsf/code/TensorRT-LLM/Qwen-TensorRT-LLM-v0.5.0/Qwen-TensorRT-LLM/qwen/weight.py", line 1003, in process_and_assign_weight
    amax = model_params[mPrefix + ".weight_quantizer._amax"].reshape(
KeyError: 'lm_head.weight_quantizer._amax'

**Comment by zshfeng00** [comment]
0.5.0版本支持int4_awq吗

**Comment by Tlntin** [comment]
安装的ammo版本是多少呢？是0.3.0吗？
感觉是ammo量化的权重不太对。

**Comment by Dujianhua1008** [comment]
请问是什么硬件 V100支持INt4 AWQ量化吗

**Comment by zshfeng00** [comment]
> 安装的ammo版本是多少呢？是0.3.0吗？ 感觉是ammo量化的权重不太对。

0.5.1

**Comment by Tlntin** [comment]
> > 安装的ammo版本是多少呢？是0.3.0吗？ 感觉是ammo量化的权重不太对。
> 
> 0.5.1

我记得readme部分有提供一个0.3.0的ammo，可以用那个试试。

**Comment by Tlntin** [comment]
> 请问是什么硬件 V100支持INt4 AWQ量化吗

试试就知道了，V100应该在支持范围内。

**Comment by zshfeng00** [comment]
> > > 安装的ammo版本是多少呢？是0.3.0吗？ 感觉是ammo量化的权重不太对。
> > 
> > 
> > 0.5.1
> 
> 我记得readme部分有提供一个0.3.0的ammo的压缩包，可以用那个试试。



> 0.3.0的ammo 的可以
