### ISSUE TITLE
Qwen2 编译错误

### ISSUE THREAD

**Issue by mogoxx** [Tlntin/Qwen-TensorRT-LLM#80]
使用的基础镜像
nvcr.io/nvidia/tritonserver:23.12-trtllm-python-py3

Tensor-LLM 安装
pip install tensorrt_llm-0.7.0-cp310-cp310-linux_x86_64.whl

编译命令
python build.py --hf_model_dir /app/model/Qwen1.5-14B-Chat \
                --dtype float16 \
                --remove_input_padding \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
                --use_inflight_batching \
                --max_batch_size 2 \
                --max_input_len 2048 \
                --max_output_len 2048 \
                --output_dir /app/model/trt_engines/fp16/1-gpu/

Traceback (most recent call last):
  File "/app/Qwen-TensorRT-LLM/examples/qwen2/build.py", line 13, in <module>
    from transformers.models.qwen2 import Qwen2Config, Qwen2ForCausalLM
ModuleNotFoundError: No module named 'transformers.models.qwen2'

好像是transformers 版本问题
pip list|grep tran
transformers                  4.33.1
transformers-stream-generator 0.0.4

**Comment by mogoxx** [comment]
> qwen2需要transformers 4.37.1以上

Tensor-LLM需要对应哪个版本

**Comment by Tlntin** [comment]
忽略警告即可。

**Comment by mogoxx** [comment]
> 忽略警告即可。

会报别的错误

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_common.py", line 56, in _init
    torch.classes.load_library(ft_decoder_lib)
  File "/usr/local/lib/python3.10/dist-packages/torch/_classes.py", line 51, in load_library
    torch.ops.load_library(path)
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libth_common.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/Qwen-TensorRT-LLM/examples/qwen2/build.py", line 15, in <module>
    from model import Qwen2ForCausalLM as Qwen2ForCausalLM_TRT
  File "/app/Qwen-TensorRT-LLM/examples/qwen2/model.py", line 7, in <module>
    from tensorrt_llm._common import default_net, default_trtnet, precision
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/__init__.py", line 61, in <module>
    _init(log_level="error")
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_common.py", line 59, in _init
    raise ImportError(str(e) + msg)
ImportError: /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libth_common.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
FATAL: Decoding operators failed to load. This may be caused by the incompatibility between PyTorch and TensorRT-LLM. Please rebuild and install TensorRT-LLM.

**Comment by Tlntin** [comment]
降pytorch版本到2.1
