### ISSUE TITLE
使用auto-gptq编译qwen_1_8B-Chat-int4官方报错'KeyError: 'transformer.h.0.attn.c_attn.qweight'

### ISSUE THREAD

**Issue by fmozer** [Tlntin/Qwen-TensorRT-LLM#83]
目的：使用auto-gptq编译qwen-1_8B-chat-int4
参考：本项目Readme
环境：自编译镜像
关键组件：
- Tritonserver 2.39.0
- TensorRT-LLM 0.7.0
- Qwen-TensorRT-LLM 0.7.0
- Qwen-1_8B-Chat-int4（官方下载）
- auto-gptq 0.7.1 （包含其它依赖，其中transform 4.37）

编译命令：
```shell
python3 build.py \
--use_weight_only \
--weight_only_precision int4_gptq \
--per_group \
--hf_model_dir qwen-1_8B-Chat-int4 \
--quant_ckpt_path qwen-1_8B-Chat-int4
```

过程报错：
```
loading attention weight...:   0%|                       | 0/24 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/qwen/build.py", line 770, in <module>
    build(0, args)
  File "/root/qwen/build.py", line 735, in build
    engine = build_rank_engine(
  File "/root/qwen/build.py", line 559, in build_rank_engine
    load_func(tensorrt_llm_qwen=tensorrt_llm_qwen,
  File "/root/qwen/weight.py", line 803, in load_from_gptq_qwen
    qkv_part = model_params[prefix + "c_attn." + suf].cpu()
KeyError: 'transformer.h.0.attn.c_attn.qweight'
```
请问大佬能否给个解决思路？

**Comment by Tlntin** [comment]
会不会是你下载的是qwen1.5(qwen2)?

**Comment by Tlntin** [comment]
这个是魔搭的，不是huggingface哈，可能模型权重略有区别。

**Comment by fmozer** [comment]
> 这个是魔搭的，不是huggingface哈，可能模型权重略有区别。没测试过魔搭的。

呃 …… ReadMe里我没注意，我换下模型试试。有结果了再来回复。再次感谢。

**Comment by fmozer** [comment]
> > 这个是魔搭的，不是huggingface哈，可能模型权重略有区别。没测试过魔搭的。
> 
> 呃 …… ReadMe里我没注意，我换下模型试试。有结果了再来回复。再次感谢。

验证成功了，`huggingface`的模型OK（下载有点困难，梯子也不管用）。`modelscope`的模型权重不同需要修改……
另外，目录名称必须保持下载时目录一致。
```
[03/11/2024-08:54:31] [TRT] [I] Engine generation completed in 32.0493 seconds.
[03/11/2024-08:54:31] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 1187 MiB, GPU 6193 MiB
[03/11/2024-08:54:31] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +0, GPU +1786, now: CPU 0, GPU 1786 (MiB)
[03/11/2024-08:54:32] [TRT] [I] [MemUsageStats] Peak memory usage during Engine building and serialization: CPU: 7929 MiB
[03/11/2024-08:54:32] [TRT-LLM] [I] Total time of building qwen_float16_tp1_rank0.engine: 00:00:32
[03/11/2024-08:54:32] [TRT-LLM] [I] Config saved to /root/qwen/trt_engines/fp16/1-gpu/config.json.
[03/11/2024-08:54:32] [TRT-LLM] [I] Serializing engine to /root/qwen/trt_engines/fp16/1-gpu/qwen_float16_tp1_rank0.engine...
[03/11/2024-08:54:33] [TRT-LLM] [I] Engine serialized. Total time: 00:00:00
[03/11/2024-08:54:33] [TRT] [I] Serialized 59 bytes of code generator cache.
[03/11/2024-08:54:33] [TRT] [I] Serialized 43109 bytes of compilation cache.
[03/11/2024-08:54:33] [TRT] [I] Serialized 211 timing cache entries
[03/11/2024-08:54:33] [TRT-LLM] [I] Timing cache serialized to /root/qwen/trt_engines/fp16/1-gpu/model.cache
[03/11/2024-08:54:33] [TRT-LLM] [I] Total time of building all 1 engines: 00:00:50
root@8ff7cfe7be52:~/qwen#
root@8ff7cfe7be52:~/qwen# python3 run.py --tokenizer_dir=Qwen-1_8B-Chat-Int4
Loading engine from /root/qwen/trt_engines/fp16/1-gpu/qwen_float16_tp1_rank0.engine
Input: "<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
你好，请问你叫什么？<|im_end|>
<|im_start|>assistant
"
Output: "我是来自阿里云的大规模语言模型，我叫通义千问。"
root@8ff7cfe7be52:~/qwen#
```
